### ISSUE TITLE
AppendElement ne createElement.

### ISSUE THREAD

**Issue by Miuey** [Miuey/happytree#22]
There is a bit confuse about the element created in `TreeManager.createElement()`.
---
- [x] Change implementation of `TreeManager.createElement()` to not append the element created on the tree. This method only must create `Element`
- [x] Create a method `appendElement(Element element, Element parent)` in TreeManager to append the `Element` to the tree:
- - [x] If the method's argument is null or not found, then the `Element` stays in a root level.
- - [x] Else the `Element` stays inside the parent passed through the method's argument.

**Comment by diegonobrega** [comment]
The second argument of `appendElement` is not necessary.
