### ISSUE TITLE
Session Object

### ISSUE THREAD

**Issue by Miuey** [Miuey/happytree#6]
Now, the current implementation of HappyTree is basically a Composite Design Pattern which the structure represents a tree of elements that the root of tree is just a single element containing the list of its children. This adaptive consists to remove this current root structure and replace by a TreeSession object. So, the root of tree will be a TreeSession object containing a list of elements (children), representing a session having 0 or N trees, instead a simple root containing only one tree, according to planed and designed.

**Comment by Miuey** [comment]
- [ ] Exclude current validation that it doesn't allow initialize session twice because an error saying that there is already a session activated shows up.
- [ ] Change TreeTransaction method name for sessionCheckout() instead sessionChekin()

**Comment by diegonobrega** [comment]
Done.
